#!/usr/bin/env bash

set -euo pipefail

cargo clippy --target i686-unknown-linux-gnu -- -D warnings
cargo fmt -- --quiet --check

find -name '*.md' \
  | xargs dirname \
  | sort -u \
  | xargs -I '{}' sh -c 'cd {} && mdsh --frozen -i *.md' \
  |& grep -Ev "^(Using input=|\[> )" || true
