#!/usr/bin/env bash

set -euo pipefail

cargo clippy --target i686-unknown-linux-gnu -- -D warnings
cargo fmt -- --quiet --check

# Skipping either of thse checks is OK if the tool isn't installed.
if command -v mdsh >/dev/null; then
  scripts/check-mdsh.bash
fi
if command -v shellcheck >/dev/null; then
  shellcheck .githooks/pre-commit scripts/*sh
fi
