name: Build and Deploy Docs
on:
  push:
    branches:
      - 'main'
env:
  CARGO_TERM_COLOR: always
jobs:
  build-and-upload:
    name: Build and Upload Docs Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Cache Nix
        id: cache-nix
        uses: mtoohey31/cache-flake-attrs@v2
        with:
          key: ${{ runner.os }}-nix-${{ hashFiles('nix/flake.lock', 'nix/flake.nix', 'rust-toolchain.toml') }}
          flake_paths: ./nix#devShells.x86_64-linux.build
      - name: Build Docs
        id: docs
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop ./nix#build -i -k CARGO_TERM_COLOR -c make docs
      - name: Upload Docs Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs
  deploy:
    # This is a separate job so we're not running everything else with the
    # additional permissions required for the deploy step.
    name: Deploy Docs
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Deploy Docs to GitHub Pages
        uses: actions/deploy-pages@v4
